"""
Mesh export module for Meshine Shop.

Converts the pipeline's mesh output into standard 3D formats that any
modeling tool (Blender, Unity, Unreal) can import. This is the final
user-facing step of the pipeline.

Source mesh formats supported (all loaded via trimesh):
    - OBJ (.obj)   — Phase 2b output with UV coordinates (meshed_uv.obj)
    - PLY (.ply)   — Decimated-only fallback if UV unwrapping was skipped

Supported export formats:
    - OBJ (.obj)        — Universal format, widest compatibility
    - glTF Binary (.glb) — Modern standard, preferred by web and game engines

Uses trimesh for format conversion. trimesh handles vertex/face data
translation between formats, preserving UV coordinates and normals when present.
The UV coordinates generated by Phase 2b's xatlas unwrapping are carried through
to the exported file automatically via trimesh's OBJ → glTF conversion path.
"""

from pathlib import Path
import trimesh


def load_mesh_info(source_mesh: Path) -> dict:
    """
    Load a mesh file and return summary information for the UI.

    Accepts any format supported by trimesh (PLY, OBJ, etc.).

    Returns a dict with:
        - vertices: int — number of vertices in the mesh
        - triangles: int — number of triangular faces
        - file_size_mb: float — source file size in megabytes

    This is called when the pipeline completes so the Export view can
    display mesh stats before the user decides on an export format.
    """
    mesh = trimesh.load(source_mesh)

    return {
        "vertices": len(mesh.vertices),
        "triangles": len(mesh.faces),
        "file_size_mb": round(source_mesh.stat().st_size / (1024 * 1024), 2),
    }


def export_mesh(source_mesh: Path, dest_path: Path) -> None:
    """
    Convert a mesh file to the format implied by dest_path's extension.

    The source may be a PLY or OBJ file — trimesh handles both. When the
    source is the Phase 2b UV-unwrapped OBJ (meshed_uv.obj), UV coordinates
    are preserved in the export (OBJ keeps vt lines; glTF includes a UV
    accessor in the mesh primitive).

    Args:
        source_mesh: Path to the pipeline's output mesh (OBJ or PLY).
        dest_path:   Where to save the exported file. The file extension
                     determines the format (.obj → OBJ, .glb → glTF Binary).

    Raises:
        ValueError: If the destination extension isn't a supported format.
        FileNotFoundError: If the source mesh doesn't exist.

    trimesh infers the export format from the file extension, so we just
    need to validate that the extension is one we support and let trimesh
    handle the actual conversion.
    """
    supported = {".obj", ".glb"}

    if not source_mesh.exists():
        raise FileNotFoundError(f"Source mesh not found: {source_mesh}")

    extension = dest_path.suffix.lower()
    if extension not in supported:
        raise ValueError(
            f"Unsupported export format '{extension}'. "
            f"Supported: {', '.join(sorted(supported))}"
        )

    # Load the mesh — trimesh auto-detects format from file extension.
    # OBJ files with UV coordinates are loaded with TextureVisuals intact.
    mesh = trimesh.load(source_mesh)

    # Export to the target format. trimesh uses the file extension to
    # determine the output format automatically.
    mesh.export(str(dest_path))
